pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'SitecoreBlazorHosted.sln'
  buildConfigurationClient: 'BlazorClient'
  buildConfigurationServer: 'BlazorServer'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.1.201

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'

- script: dotnet build --configuration $(buildConfigurationClient) SitecoreBlazorHosted.Client/SitecoreBlazorHosted.Client.csproj
  displayName: 'Building $(buildConfigurationClient)...'

- script: dotnet build --configuration $(buildConfigurationServer) SitecoreBlazorHosted.Server/SitecoreBlazorHosted.Server.csproj
  displayName: 'Building $(buildConfigurationServer)...'

- task: DotNetCoreCLI@1
  displayName: 'Running tests...'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfigurationClient)'


