trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfigurationClient: 'BlazorClient'
  buildConfigurationServer: 'BlazorServer'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview4-011223

- script: dotnet build --configuration $(buildConfigurationClient) SitecoreBlazorHosted.Client/SitecoreBlazorHosted.Client.csproj
  displayName: 'Building $(buildConfigurationClient)...'

- script: dotnet build --configuration $(buildConfigurationServer) SitecoreBlazorHosted.Server/SitecoreBlazorHosted.Server.csproj
  displayName: 'Building $(buildConfigurationServer)...'
