trigger:
- Upgrading-to-3.0.0-preview4-19216-03

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfigurationClient: 'BlazorClient'
  buildConfigurationServer: 'BlazorServer'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview4-011223

- script: dotnet build --configuration $(buildConfiguration) SitecoreBlazorHosted.Client/SitecoreBlazorHosted.Client.csproj
  displayName: 'Building $(buildConfigurationClient)...'

- script: dotnet build --configuration $(buildConfiguration) SitecoreBlazorHosted.Server/SitecoreBlazorHosted.Server.csproj
  displayName: 'Building $(buildConfigurationServer)...'

#variables:
#  solution: '**/*.sln'
#  buildPlatform: 'Any CPU'
#  buildConfiguration: 'BlazorClient'
#  projects: '**/*.csproj'

#steps:
#- task: DotNetCoreCLI@2
#  displayName: Test
#  inputs:
#    command: build
#    projects: '**/*.csproj'
#    arguments: '--configuration $(BuildConfiguration)'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
# displayName: 'dotnet build $(buildConfiguration)'


#steps:
#- task: DotNetCoreCLI@1
#  displayName: Build
#  inputs:
#    version: '3.0.100-preview4-011223'
#    command: build
#    projects: '**/*.csproj'
#    arguments: '--configuration Release'
